server:
  port: 8888

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-idle: 30
        max-wait: 10000
        min-idle: 10